### ISSUE TITLE
Handle Bad Responses

### ISSUE THREAD

**Issue by sethvargo** [berkshelf/berkshelf#912]
- [ ] "Invalid file" thrown by Chef 11 when files are in the wrong directories (#894)
- [x] "bad response" when the API server is down (#911, #843)
- [x] Exceptions from Git (#879)
